name             "devbox"
maintainer       "lethalpaga"
maintainer_email "lethalpaga@gmail.com"
license          "Apache 2.0"
description      "Installs a base dev box"
long_description "Installs a base dev box"
version          "0.0.1"

depends          "rvm"
depends          "vim_config"
depends          "golang"